#' Principal Components, Dygraphs, Forecasts, Seasonal Adjustment
#' 
#' Example Functions, Generated by [ts_]. `ts_prcomp` calculates the principal
#' components of multiple time series, `ts_dygraphs` generates an interactive
#' graphical visualization, `ts_forecast` return an univariate forecast,
#' `ts_seas` the seasonally adjusted series.
#' 
#' With the exception of `ts_prcomp`, these functions depend on external
#' packages.
#'
#' @param x ts-boxable time series, an object of class `ts`, `xts`, `data.frame`, `data.table`, or `tibble`.
#' @param ... further arguments, passed to the underlying function. For help, consider these functions, e.g., [stats::prcomp].
#'
#' @return Usually, a ts-boxable time series, with the same class as the input. `ts_dygraphs` draws a plot.
#' 
#' @examples
#' ts_prcomp(ts_c(mdeaths, fdeaths))
#' ts_dygraphs(ts_c(mdeaths, EuStockMarkets))
#' ts_forecast(ts_c(mdeaths, fdeaths))
#' ts_seas(ts_c(mdeaths, fdeaths))
#'
#' @export
#' @name ts_examples
ts_prcomp <- ts_(function(x) predict(prcomp(x, scale = TRUE)))

#' @export
#' @name ts_examples
ts_dygraphs <- ts_(dygraphs::dygraph, class = "xts", reclass = FALSE)

#' @export
#' @name ts_examples
ts_forecast <- ts_(function(x) forecast::forecast(x)$mean, vectorize = TRUE)

#' @export
#' @name ts_examples
ts_seas <- ts_(function(x) seasonal::final(seasonal::seas(x)), vectorize = TRUE)
