#' Useful functions, generated by `ts_`
#' 
#' @param x a ts-boxable object
#' @param ... further arguments, passed to functions
#' 
#' 
#' @examples
#' ts_prcomp(ts_c(mdeaths, fdeaths))
#' ts_dygraphs(ts_c(mdeaths, EuStockMarkets))
#' ts_forecast(ts_c(mdeaths, fdeaths))
#' ts_seas(ts_c(mdeaths, fdeaths))
#'
#' @export
#' @name ts_misc
ts_prcomp <- ts_(function(x) predict(prcomp(x, scale = TRUE)))

#' @export
#' @name ts_misc
ts_dygraphs <- ts_(dygraphs::dygraph, class = "xts")

#' @export
#' @name ts_misc
ts_forecast <- ts_(function(x) forecast::forecast(x)$mean, vectorize = TRUE)

#' @export
#' @name ts_misc
ts_seas <- ts_(function(x) seasonal::final(seasonal::seas(x)), vectorize = TRUE)
