#' Lags, Differences, Percentage Change Rates
#'
#' Utlility functions to work with time series. `ts_pcy` and `ts_diffy` calulate
#' the percentage change and the difference compared to the same period of the
#' previous year, rather than the previous period. `ts_index` returns an index 
#' series, with value of 1 at `base` date.
#' 
#' @param x ts-boxable time series, an object of class `ts`, `xts`, `data.frame`, `data.table`, or `tibble`.
#' @param lag integer, the number of lags. This is defined as in dplyr, opposite to R base.
#' @param fill how to fill missing values
#' @param ... additional arguments, passed to subfunctions (as some of these functions are generated by [ts_])
#' @return a ts-boxable time series, with the same class as the input.
#' @examples
#' ts_lag(ts_c(fdeaths, mdeaths))
#' ts_diff(ts_c(fdeaths, mdeaths))
#' ts_pc(ts_c(fdeaths, mdeaths))
#' ts_index(ts_df(ts_c(fdeaths, mdeaths)), "1977-01-01")
#' @export
ts_lag <- function(x, lag = 1, fill = NA) {
  value <- NULL
  z <- ts_dts(x)
  z <- ts_regular(z)

  if (lag < 0) {
    .type <- "lead"
    lag <- -lag
  } else {
    .type <- "lag"
  }

  colname.id <- colname_id(z)
  .by <- parse(text = paste0("list(", paste(colname.id, collapse = ", "), ")"))

  # do not use ts_apply here, to take advantage of data.table speed
  z[
    ,
    value := shift(value, n = lag, fill = fill, type = .type, give.names = FALSE),
    by = eval(.by)
  ]

  ts_na_omit(copy_class(z, x))
}


#' @name ts_lag
#' @export
ts_pc <- function(x) {
  value <- NULL
  z <- ts_dts(x)
  z <- ts_regular(z)

  colname.id <- colname_id(z)
  colname.value <- colname_value(z)
  setnames(z, colname.value, "value")
  .by <- parse(text = paste0("list(", paste(colname.id, collapse = ", "), ")"))
  z[
    ,
    value := 100 * (value / shift(value) - 1),
    by = eval(.by)
  ]
  setnames(z, "value", colname.value)
  ts_na_omit(copy_class(z, x))
}

#' @name ts_lag
#' @export
ts_diff <- function(x) {
  value <- NULL
  z <- ts_dts(x)
  z <- ts_regular(z)

  colname.id <- colname_id(z)
  colname.value <- colname_value(z)

  setnames(z, colname.value, "value")
  .by <- parse(text = paste0("list(", paste(colname.id, collapse = ", "), ")"))
  z[
    ,
    value := value / shift(value) - 1,
    by = eval(.by)
  ]
  setnames(z, "value", colname.value)
  ts_na_omit(copy_class(z, x))
}


#' @name ts_lag
#' @param base base date, character string, `Date` or `POSIXct`, at which the 
#'   value will be set to 1.
#' @export
ts_index <- function(x, base) {
  base <- anydate(as.character(base))

  not_in_data <- NULL
  value <- NULL
  z <- ts_dts(x)

  colname.id <- colname_id(z)
  colname.value <- colname_value(z)
  colname.time <- colname_time(z)
  setnames(z, colname.time, "time")
  setnames(z, colname.value, "value")

  if (inherits(z$time, "POSIXct")){
    stop("indexing only works on 'Date', not 'POSIXct'")
  }

  .by <- parse(text = paste0("list(", paste(colname.id, collapse = ", "), ")"))
  
  # check if base date in data (rewrite)
  dt_in_data <- z[
    ,
    list(not_in_data = !(base %in% time)),
    by = eval(.by)
  ]
  if (any(dt_in_data$not_in_data)){
    cname.id <- colname_id(z)
    if (NCOL(z) > 3) {
      id.missing <- combine_cols_data.table(
        dt_in_data[not_in_data == TRUE], colname_id
      )$id
    } else if (NCOL(z) == 3) {
      id.missing <- dt_in_data[not_in_data == TRUE][[cname.id]]
    } 

    if (length(cname.id) == 0) {
      stop(base, " not in series", call. = FALSE)
    } else {
      stop(
        base, " not in series: ",
        paste(id.missing, collapse = ", "), 
        call. = FALSE
      )
    }
  }
  z[
    ,
    value := value / .SD[time == base, value],
    by = eval(.by)
  ]
  setnames(z, "value", colname.value)
  setnames(z, "time", colname.time)
  ts_na_omit(copy_class(z, x))

}


# This should also make use of data.table::shift, also don't do series by series
# need function for frequency detection fo regular dts

pcy_core <- function(x) {
  100 * ((x / stats::lag(x, -frequency(x))) - 1)
}

#' @name ts_lag
#' @export
ts_pcy <- ts_(pcy_core, vectorize = TRUE)

#' @name ts_lag
#' @export
ts_diffy <- ts_(function(x) diff(x, lag = frequency(x)), vectorize = TRUE)


